# Generated by Django 4.2.2 on 2024-02-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeviceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_ip", models.CharField(max_length=255)),
                ("device_id", models.CharField(max_length=255)),
                ("device_key", models.CharField(max_length=255)),
            ],
        ),
    ]
